Clean clean
teragrep/zep_01 pull request #24
Opened 2024-09-30 12:33 UTC by StrongestNumber9

Should fix #14 but not yet tested
Fixes #16 by ignoring them for now  
Removes test related to #17

2024-09-30 12:34 UTC, StrongestNumber9 commented
This is a draft for now but current github plan won't allow private repo to have draft PRs

2024-10-25 12:55 UTC, kortemik commented on spark/interpreter/src/test/java/org/apache/zeppelin/spark/SparkShimsTest.java
why is this being removed?

2024-10-25 12:55 UTC, kortemik commented on zeppelin-display/pom.xml
does %angular work if display is removed?

2024-10-25 12:55 UTC, kortemik commented on zeppelin-distribution/pom.xml
zeppelin-distribution looks like something debian based stuff, do we need it?

2024-10-28 06:44 UTC, StrongestNumber9 commented on zeppelin-display/pom.xml
Zeppelin-display was merged with spark in upstream and I took the 0.11.x based python/spark interpreters from upstream to have even the slightest chance of getting it to build in somewhat reasonable time

2024-10-28 06:44 UTC, StrongestNumber9 commented on zeppelin-distribution/pom.xml
Not sure at all, I think that is the thing that builds the zip but this whole project is a mess

2024-10-28 06:49 UTC, StrongestNumber9 commented on spark/interpreter/src/test/java/org/apache/zeppelin/spark/SparkShimsTest.java
I think there was an issue with them (at some point), will have to investigate

2024-10-28 06:55 UTC, StrongestNumber9 commented on zeppelin-display/pom.xml
Note that the zeppelin server and such was left as-is and are based on 0.10.1, just that the interpreters had so many spark related upgrades that it seemed a lot more reasonable this way

2024-10-28 07:31 UTC, StrongestNumber9 commented on spark/interpreter/src/test/java/org/apache/zeppelin/spark/SparkShimsTest.java
Seems like it was dependency issues, I'll check the upstream main pom.xml if theres some versioning differences

```
zep_01-migrate/spark/interpreter/src/test/java/org/apache/zeppelin/spark/SparkShimsTest.java:44: error: package org.powermock.core.classloader.annotations does not exist
import org.powermock.core.classloader.annotations.PowerMockIgnore;
                                                 ^
zep_01-migrate/spark/interpreter/src/test/java/org/apache/zeppelin/spark/SparkShimsTest.java:45: error: package org.powermock.core.classloader.annotations does not exist
import org.powermock.core.classloader.annotations.PrepareForTest;
                                                 ^
zep_01-migrate/spark/interpreter/src/test/java/org/apache/zeppelin/spark/SparkShimsTest.java:46: error: package org.powermock.modules.junit4 does not exist
import org.powermock.modules.junit4.PowerMockRunner;
                                   ^
zep_01-migrate/spark/interpreter/src/test/java/org/apache/zeppelin/spark/SparkShimsTest.java:112: error: cannot find symbol
  @PrepareForTest({ZeppelinContext.class, VersionInfo.class})
   ^
  symbol:   class PrepareForTest
  location: class SparkShimsTest
zep_01-migrate/spark/interpreter/src/test/java/org/apache/zeppelin/spark/SparkShimsTest.java:113: error: cannot find symbol
  @PowerMockIgnore({"javax.net.*", "javax.security.*"})
   ^
  symbol:   class PowerMockIgnore
  location: class SparkShimsTest
zep_01-migrate/spark/interpreter/src/test/java/org/apache/zeppelin/spark/SparkShimsTest.java:111: error: cannot find symbol
  @RunWith(PowerMockRunner.class)
           ^
  symbol:   class PowerMockRunner
  location: class SparkShimsTest
```

2024-10-28 07:40 UTC, StrongestNumber9 commented on spark/interpreter/src/test/java/org/apache/zeppelin/spark/SparkShimsTest.java
Ah right, it was updated in upstream but there are java version(?) issues, will have to check

```sh
zep_01-migrate/spark/interpreter/src/test/java/org/apache/zeppelin/spark/SparkInterpreterTest.java:175: warning: [rawtypes] found raw type: Map
    ArgumentCaptor<Map> captorEvent = ArgumentCaptor.forClass(Map.class);
                   ^
  missing type arguments for generic class Map<K,V>
  where K,V are type-variables:
    K extends Object declared in interface Map
    V extends Object declared in interface Map
```

```
spark/interpreter/src/test/java/org/apache/zeppelin/spark/SparkInterpreterTest.java:176: warning: [unchecked] unchecked method invocation: method onParaInfosReceived in class RemoteInterpreterEventClient is applied to given types
    verify(mockRemoteEventClient).onParaInfosReceived(captorEvent.capture());
                                                     ^
  required: Map<String,String>
  found: Map
```

and such

2024-10-28 07:57 UTC, kortemik commented on spark/interpreter/src/test/java/org/apache/zeppelin/spark/SparkShimsTest.java
is upstream java11+ only?

2024-10-28 11:30 UTC, StrongestNumber9 commented on spark/interpreter/src/test/java/org/apache/zeppelin/spark/SparkShimsTest.java
Issue was outdated mockito version, fixed in the newest commit

2024-10-30 09:56 UTC, StrongestNumber9 commented on zeppelin-display/pom.xml
It indeed is missing when using `%angular`, looking into it

2024-10-30 11:24 UTC, StrongestNumber9 commented on zeppelin-display/pom.xml
Readded angular interpreter by introducing it, not sure why it was removed in the first place

2024-11-05 11:34 UTC, StrongestNumber9 commented
I tried to leave `zeppelin-*` components as alone as possible. Interpreters are updated to upstream 0.11.2 version and then manually edited back to 0.10.1. Interpreters were mostly edited to make tests pass, fix dependencies or remove support for components like jupyter and such

2024-11-05 11:39 UTC, StrongestNumber9 commented on markdown/src/main/java/org/apache/zeppelin/markdown/FlexmarkParser.java
> +    options.set(HtmlRenderer.ESCAPE_HTML, true);
Was made to avoid having to update zeppelin-server that provides zConf for whether it is enabled or not

2024-11-05 11:40 UTC, StrongestNumber9 commented on markdown/src/main/java/org/apache/zeppelin/markdown/FlexmarkParser.java
> -            UMLExtension.create(),
Removes support for UML extensions as we do not want them

2024-11-05 13:19 UTC, kortemik requested changes

2024-11-05 13:19 UTC, kortemik commented on jdbc/src/main/java/org/apache/zeppelin/jdbc/security/JDBCSecurityImpl.java
> +                "will check tgt and whether to re-login");
log before the call.

2024-11-05 13:19 UTC, kortemik commented on zeppelin-interpreter-integration/pom.xml
do not remove integration tests

2024-11-05 13:19 UTC, kortemik commented on zeppelin-server/src/test/java/org/apache/zeppelin/cluster/ClusterEventTest.java
do not remove tests

2024-11-05 13:21 UTC, StrongestNumber9 commented on zeppelin-interpreter-integration/pom.xml
I can re-add them but they are/were fairly fragile and often got stuck

2024-11-05 13:21 UTC, StrongestNumber9 commented on jdbc/src/main/java/org/apache/zeppelin/jdbc/security/JDBCSecurityImpl.java
> +                "will check tgt and whether to re-login");
Change from upstream, I can still fix it if wanted

2024-11-05 13:22 UTC, StrongestNumber9 commented on zeppelin-server/src/test/java/org/apache/zeppelin/cluster/ClusterEventTest.java
I can re-add them but they are/were fairly fragile and often got stuck

2024-11-12 13:47 UTC, kortemik requested changes

2024-11-12 13:47 UTC, kortemik commented on zeppelin-server/src/test/java/org/apache/zeppelin/cluster/ClusterEventTest.java
restore deleted tests

2024-11-13 06:03 UTC, StrongestNumber9 commented on zeppelin-server/src/test/java/org/apache/zeppelin/cluster/ClusterEventTest.java
These tests are now restored by reverting the commit

2024-11-13 06:26 UTC, StrongestNumber9 commented on zeppelin-interpreter-integration/pom.xml
Integration tests re-added but left the activation profile for now

2024-11-13 06:28 UTC, StrongestNumber9 commented on jdbc/src/main/java/org/apache/zeppelin/jdbc/security/JDBCSecurityImpl.java
> +                "will check tgt and whether to re-login");
Pushed a fix for it

2024-11-13 06:54 UTC, StrongestNumber9 commented on zeppelin-distribution/pom.xml
Debian related parts are removed and it is currently fairly small version of what it used to be. It should be removed eventually once more cleanup is being done

2024-11-13 06:55 UTC, StrongestNumber9 commented on zeppelin-server/src/test/java/org/apache/zeppelin/cluster/ClusterEventTest.java
They are re-added now

2024-11-13 06:57 UTC, StrongestNumber9 commented
The commit 3d38e8d4247769c3fbdef7318a80fae3a83e88bf is a hack but might be acceptable if dependency upgrades are happening anyways

2024-11-13 13:24 UTC, StrongestNumber9 commented
Seems to be building again as of commit d4e76a6e665861d79c2818d39e9f396f1fcfeeee

2024-11-13 14:50 UTC, kortemik commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/interpreter/launcher/SparkInterpreterLauncherTest.java
> -public class SparkInterpreterLauncherTest {
is this intentional deletion, and why?

2024-11-14 04:54 UTC, StrongestNumber9 commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/interpreter/launcher/SparkInterpreterLauncherTest.java
> -public class SparkInterpreterLauncherTest {
I believe this was due to it being spark 2.x testing as seen in the other comment

2024-11-14 04:55 UTC, StrongestNumber9 commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/interpreter/launcher/SparkInterpreterLauncherTest.java
> -    sparkHome = DownloadUtils.downloadSpark("2.4.4", "2.7");
Spark 2.x here

2024-11-14 04:55 UTC, StrongestNumber9 commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/interpreter/launcher/SparkInterpreterLauncherTest.java
> -public class SparkInterpreterLauncherTest {
I'll restore, verify and ignore the tests if necessary

2024-11-14 05:09 UTC, StrongestNumber9 commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/interpreter/launcher/SparkInterpreterLauncherTest.java
> -public class SparkInterpreterLauncherTest {
It was in commit 74f950f3206cba6ed61677622ff203dd6cc8e5d6 that resolves arbitrary dependencies on runtime. I'll revert and ignore them

2024-11-14 05:23 UTC, StrongestNumber9 commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/interpreter/launcher/SparkInterpreterLauncherTest.java
> -public class SparkInterpreterLauncherTest {
They are now reverted but ignored

2024-11-14 12:37 UTC, kortemik commented on zeppelin-interpreter/src/test/java/org/apache/zeppelin/dep/DependencyResolverTest.java
please create an issue about removing the whole dependency resolver along with it's tests

2024-11-14 12:37 UTC, kortemik commented on zeppelin-interpreter/src/test/java/org/apache/zeppelin/display/AngularObjectTest.java
> +import org.junit.Ignore;
create issue about converting all to junit5, Ignore is junit4 syntax for junit5 disabled

2024-11-14 12:41 UTC, StrongestNumber9 commented on zeppelin-interpreter/src/test/java/org/apache/zeppelin/dep/DependencyResolverTest.java
Done

2024-11-14 12:41 UTC, StrongestNumber9 commented on zeppelin-interpreter/src/test/java/org/apache/zeppelin/display/AngularObjectTest.java
> +import org.junit.Ignore;
Done

2024-11-14 12:43 UTC, merged