Remove dependency resolver, helium and references to them in configur…
teragrep/zep_01 pull request #55
Opened 2024-11-20 09:13 UTC by StrongestNumber9

…ation

Fixes #36

2024-11-22 13:41 UTC, Laukkala reviewed
Deletions look good to me. Doesn't look like anything essential was removed.

2024-11-25 11:27 UTC, kortemik requested changes

2024-11-25 11:27 UTC, kortemik commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/interpreter/launcher/SparkInterpreterLauncherTest.java
> -    String sparkJars = "jar_1," +
why these are removed?

2024-11-25 11:35 UTC, StrongestNumber9 commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/interpreter/launcher/SparkInterpreterLauncherTest.java
> -    String sparkJars = "jar_1," +
Seems like I have removed too much and should hav removed only the local repo part of it

2024-11-25 11:38 UTC, StrongestNumber9 commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/interpreter/launcher/SparkInterpreterLauncherTest.java
> -    String sparkJars = "jar_1," +
Seems like I have also disabled this test due to

`@Ignore("This test is broken: java.lang.RuntimeException: No such note: note1")`

Was wondering why it hadn't broken the test, most likely related to issue #34

2024-12-02 07:26 UTC, StrongestNumber9 commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/interpreter/launcher/SparkInterpreterLauncherTest.java
> -    String sparkJars = "jar_1," +
That is now readded by commit f616b3f74d597a50c66cd205a6a0d02bb4856bd5

2024-12-02 09:06 UTC, kortemik approved these changes

2024-12-02 09:07 UTC, merged