Remove more unnecessary cleanups
teragrep/zep_01 pull request #77
Opened 2024-12-17 08:34 UTC by StrongestNumber9

Vast majority of the changes are newline changes since a lot of try/catches are removed
Re-enables bunch of tests
Removes a lot of manual cleanups that makes tests affect each other

2024-12-18 09:06 UTC, kortemik requested changes

2024-12-18 09:06 UTC, kortemik commented on jdbc/src/test/java/org/apache/zeppelin/jdbc/JDBCInterpreterTest.java
> +  @Disabled(value="Cotnains bunch of sleeps and awaits")
typo, please fix

2024-12-18 09:06 UTC, kortemik commented on zeppelin-server/src/test/java/org/apache/zeppelin/recovery/RecoveryTest.java
> +@Ignore(value="Tets will fail at notebook.createNote with a 'IndexOutOfBounds Index 0 out of bounds for length 0' message, might be relics of test-to-test contamination")
typo, please fix

2024-12-18 09:06 UTC, kortemik commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/interpreter/remote/AppendOutputRunnerTest.java
> -  @After
i think this should be a fail if test leaves open futures behind

2024-12-18 09:06 UTC, kortemik commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/interpreter/remote/RemoteInterpreterTest.java
> -      System.clearProperty(ZeppelinConfiguration.ConfVars.ZEPPELIN_INTERPRETER_REMOTE_RUNNER.getVarName());
test should clear properties they set

2024-12-18 09:06 UTC, kortemik commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/notebook/NotebookTest.java
> -    System.clearProperty(ConfVars.ZEPPELIN_NOTEBOOK_PUBLIC.getVarName());
tests should clear properties they set, although these should never be needed but a local properties instance should be used

2024-12-18 09:06 UTC, kortemik commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/scheduler/RemoteSchedulerTest.java
> -    schedulerSvc = SchedulerFactory.singleton();
why removing this, it is essential to throw if notebooks are still scheduled when the test ends

2024-12-18 14:08 UTC, StrongestNumber9 commented on jdbc/src/test/java/org/apache/zeppelin/jdbc/JDBCInterpreterTest.java
> +  @Disabled(value="Cotnains bunch of sleeps and awaits")
Fixed in 64938030fe1948e48ee879c46b4bbccbec231824

2024-12-18 14:08 UTC, StrongestNumber9 commented on zeppelin-server/src/test/java/org/apache/zeppelin/recovery/RecoveryTest.java
> +@Ignore(value="Tets will fail at notebook.createNote with a 'IndexOutOfBounds Index 0 out of bounds for length 0' message, might be relics of test-to-test contamination")
Fixed in 64938030fe1948e48ee879c46b4bbccbec231824

2024-12-18 14:16 UTC, StrongestNumber9 commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/interpreter/remote/AppendOutputRunnerTest.java
> -  @After
Readded in commit fbe98f0aa63786b66423a6bfc9e8e3312969ab08 but without null check

2024-12-18 14:20 UTC, StrongestNumber9 commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/interpreter/remote/RemoteInterpreterTest.java
> -      System.clearProperty(ZeppelinConfiguration.ConfVars.ZEPPELIN_INTERPRETER_REMOTE_RUNNER.getVarName());
I believe tests should either clear properties on AfterEach function or set them to good values at the beginning of the test. Relying each test to clear them by themselves makes it fairly fragile and make them accidentally affect each other. However all tests edited in this PR are all depending on questionable custom interpreters and are disabled to begin with

2024-12-18 14:28 UTC, StrongestNumber9 commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/notebook/NotebookTest.java
> -    System.clearProperty(ConfVars.ZEPPELIN_NOTEBOOK_PUBLIC.getVarName());
Readded in commit cfb7abbe6836845b4ae30a097e061def8e28cc60 as these are in After function

2024-12-18 14:37 UTC, StrongestNumber9 commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/scheduler/RemoteSchedulerTest.java
> -    schedulerSvc = SchedulerFactory.singleton();
Good point, I was thinking it was more of manual cleanups that we want avoid. Readded in db26327620f856502ad7f7677e752ce092eb6af7

2024-12-19 13:38 UTC, StrongestNumber9 commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/interpreter/remote/RemoteInterpreterTest.java
> -      System.clearProperty(ZeppelinConfiguration.ConfVars.ZEPPELIN_INTERPRETER_REMOTE_RUNNER.getVarName());
Reintroduced them in 424fdd7e38e1aa27d1db0b423e3f29b7ee7e1619 but as an `@After` block so it is not test-dependent but everyone will get cleaned

2024-12-20 07:54 UTC, kortemik requested changes

2024-12-20 07:54 UTC, kortemik commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/notebook/NotebookTest.java
> -      System.setProperty(ConfVars.ZEPPELIN_NOTEBOOK_CRON_ENABLE.getVarName(), "true");
after block for this too?

2024-12-30 07:35 UTC, StrongestNumber9 commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/notebook/NotebookTest.java
> -      System.setProperty(ConfVars.ZEPPELIN_NOTEBOOK_CRON_ENABLE.getVarName(), "true");
The ZEPPELIN_NOTEBOOK_CRON_ENABLE clearing in after block was reintroduced in commit cfb7abbe6836845b4ae30a097e061def8e28cc60 but for some reason github doesn't seem to be printing the diff

2024-12-30 11:12 UTC, StrongestNumber9 commented
Added bunch of fixes suggested by IDEAs analyzing tool

2025-01-07 08:42 UTC, kortemik requested changes

2025-01-07 08:42 UTC, kortemik commented on zeppelin-server/src/test/java/org/apache/zeppelin/rest/NotebookRestApiTest.java
> -        TestUtils.getInstance(Notebook.class).removeNote(note1, anonymous);
shouldn't this be AfterEach?

2025-01-07 08:42 UTC, kortemik commented on zeppelin-server/src/test/java/org/apache/zeppelin/rest/ZeppelinRestApiTest.java
> -        TestUtils.getInstance(Notebook.class).removeNote(note, anonymous);
shouldn't this be AfterEach?

2025-01-07 08:42 UTC, kortemik commented on zeppelin-server/src/test/java/org/apache/zeppelin/socket/NotebookServerTest.java
> -        notebook.removeNote(note, anonymous);
AfterEach?

2025-01-07 08:42 UTC, kortemik commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/notebook/NotebookTest.java
> -      System.setProperty(ConfVars.ZEPPELIN_NOTEBOOK_CRON_ENABLE.getVarName(), "true");
does it remove the note as well?

2025-01-07 08:42 UTC, kortemik commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/notebook/repo/NotebookRepoSyncTest.java
> -    notebook.removeNote(notebookRepoSync.get(noteInfo.getId(), note.getPath(), anonymous), anonymous);
why does this remove the removal?

2025-01-07 10:19 UTC, StrongestNumber9 commented on zeppelin-server/src/test/java/org/apache/zeppelin/rest/NotebookRestApiTest.java
> -        TestUtils.getInstance(Notebook.class).removeNote(note1, anonymous);
No manually coded cleanups of notebooks should be necessary as they all live in their own directories. Better to leave them and let maven handle the cleanup when wanted as this will immediately alarm when tests are affected by other tests and their files in which case the tests should be fixed.

2025-01-07 10:23 UTC, StrongestNumber9 commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/notebook/repo/NotebookRepoSyncTest.java
> -    notebook.removeNote(notebookRepoSync.get(noteInfo.getId(), note.getPath(), anonymous), anonymous);
This is purely manual cleanup that is done after all assertions are execute which should not be necessary, otherwise same explanation as above. Theres already a `testSyncOnDelete` test that handles proper assertions after deletion

2025-01-07 10:27 UTC, StrongestNumber9 commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/notebook/NotebookTest.java
> -      System.setProperty(ConfVars.ZEPPELIN_NOTEBOOK_CRON_ENABLE.getVarName(), "true");
There should be no need to remove the note manually. The schedulerService maybe should be cleared/remade if necessary though.

```
private void terminateScheduledNote(Note note) throws IOException {
    note.getConfig().remove("cron");
    schedulerService.refreshCron(note.getId());
    notebook.removeNote(note, anonymous);
}
```

2025-01-07 10:53 UTC, kortemik approved these changes

2025-01-07 10:56 UTC, merged